package uk.jackbergus.ARGA.structure.locutors;

import uk.jackbergus.ARGA.logic.FOL.Formula;

/**
 * 
 */
//@uk.jackbergus.ARGA.semantics.Entity(name="algorithm")
public class Algorithm extends Locutor{

	/**
	 * Memo name for the algorithm
	 */
//	@Column(name="name")
	public String name;

	/**
	 * Properties that are assumed while running the program
	 */
	public Formula fol_requirements;

	/**
	 * Represents the effects generated by the program in terms of FOL formula
	 */
	public Formula fol_effects;

	public Algorithm(String name) {
		this.name = name;
		fol_effects = fol_requirements = null;
	}

}